spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-uf61rp63pil4tfn87o.mysql.rds.aliyuncs.com:3306/springbootdb?useUnicode=true&characterEncoding=utf8
      username: root
      password: Langjianwei1015
    redis:  
      database:  0  
      host:  192.168.245.128  
      port:  6379  
      password: 123123  
      pool:  
        max-active: 8  
        max-wait: -1  
        max-idle: 8  
        min-idle: 0  
      timeout: 0

    #Thymeleaf模板引擎配置
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html

mybatis:
     typeAliasesPackage: org.spring.springboot.domain
     mapperLocations: classpath:mapper/*.xml

server:
      port: 8088

